"""create_qa_logs_table

Revision ID: 5908ef9e76f4
Revises: 52b0a0a49068
Create Date: 2026-07-20 16:15:59.261876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5908ef9e76f4'
down_revision: Union[str, Sequence[str], None] = '52b0a0a49068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(), nullable=False),
    sa.Column('retrieved_chunk_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('citations_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('groundedness_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_logs_session_id'), 'qa_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qa_logs_session_id'), table_name='qa_logs')
    op.drop_table('qa_logs')
    # ### end Alembic commands ###
