"""add estimated_cost_usd column to qa_logs

Revision ID: a6c8d60daa4c
Revises: a9a89a24a372
Create Date: 2026-07-21 11:22:41.755140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c8d60daa4c'
down_revision: Union[str, Sequence[str], None] = 'a9a89a24a372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_logs', sa.Column('estimated_cost_usd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_logs', 'estimated_cost_usd')
    # ### end Alembic commands ###
