"""add fetch_status verified_at content_sha256 to documents

Revision ID: eeef26b00837
Revises: a6c8d60daa4c
Create Date: 2026-08-26 16:40:01.829813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeef26b00837'
down_revision: Union[str, Sequence[str], None] = 'a6c8d60daa4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'documents',
        sa.Column('fetch_status', sa.String(), nullable=False, server_default='fetched'),
    )
    op.add_column(
        'documents',
        sa.Column('verified_at', sa.DateTime(), nullable=True),
    )
    op.add_column(
        'documents',
        sa.Column('content_sha256', sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'content_sha256')
    op.drop_column('documents', 'verified_at')
    op.drop_column('documents', 'fetch_status')
    # ### end Alembic commands ###
